class hubzero_1_2 {
  include mysql_hubzero
  include exim4
  include cms
  include open-ldap
  include webdav
  include subversion
  include trac
  include forge
  include openvz
  include firewall
  include maxwell-service
  include maxwell-client
  include vncproxy
  include telequotad
  include workspace
#  include metrics # metrics for 1.2.2 is broken, the advice is not to install it...
  include rappture
  include filexfer
# include submit
# now the v3 support packages
# first off, the nagios checks
  include nrpe
  include nrpe::absolutememory
  include nrpe::apachememory
# we want the machine to install security updates automatically.
  include unattended_upgrades
# we want to have V3 admins able to access the machine
  class { 'v3::admins':
    username   => 'martin',
    user_mail  => 'mpaulo@v3.org.au',
  # generated by:  ssh-keygen -t rsa -C "${user_mail}" then copying the public portion to the key below.
    public_key => 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDMW4zLFHV0j8GgVG/5yebcs95gaCBwgv+YfTLAok/dY77LoqVGhw+4vP3A03qnc0l08Dq5BJz8x6i4JSmUgYS+tMh7MIopR6VsG3jDwt7cViJUKicWEUCwF0M8RRtdLAtVvbv3o3DrhLcEqzpGE4yO3wIYkFzFvU+wmoA4IJt95ZK3z/VXtljUs4bB8XeYfAf+gGei/y9sNcn5388LDr5Wkqay/2fXmllC7yAxeNdD5pOsDI1/xwFBYCG5wmatsJvKL5zpWQPm1LWQ0uCPZzn40t5KsFGE5puxs6uvVSpmn3k/u7qlMfYhpDIXhn63yw9Kzi9qL2PFVsbmk7Y6Z+qp',
  }
# we want to have NTP
  include '::ntp'
# we want to backup up the database
  include v3::backups
# and write the backup to swift
  include v3::duplicity
  include v3::swift
}