class v3::admins {

# for our admin's sanity
  package { 'vim':
    ensure => latest,
  }

# public key generated by:  ssh-keygen -t rsa -C "${user_mail}" then copying the public portion to the key below.
  v3::admin_account { 'v3_martin':
    user_mail  => 'mpaulo@v3.org.au',
    user_id    => '501',
    public_key => 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDMW4zLFHV0j8GgVG/5yebcs95gaCBwgv+YfTLAok/dY77LoqVGhw+4vP3A03qnc0l08Dq5BJz8x6i4JSmUgYS+tMh7MIopR6VsG3jDwt7cViJUKicWEUCwF0M8RRtdLAtVvbv3o3DrhLcEqzpGE4yO3wIYkFzFvU+wmoA4IJt95ZK3z/VXtljUs4bB8XeYfAf+gGei/y9sNcn5388LDr5Wkqay/2fXmllC7yAxeNdD5pOsDI1/xwFBYCG5wmatsJvKL5zpWQPm1LWQ0uCPZzn40t5KsFGE5puxs6uvVSpmn3k/u7qlMfYhpDIXhn63yw9Kzi9qL2PFVsbmk7Y6Z+qp',
  }
  v3::admin_account { 'v3_alan':
    user_mail  => 'alan@v3.org.au',
    user_id    => '502',
    public_key => 'AAAAB3NzaC1yc2EAAAABIwAAAQEA7UQmx4+R7ToMxZJyQmfV0xIAQ1v3WYibFHKTmLd830HVOH+iP+vWTVqLd6eCU6gdV7RmnkgJ/LMsYZC48kguyN2YBzA3+vWSexAcrKxlcNchLAbw66fwTy54jzrACRDsJw+6cXUmox/ZKIs3LTsGHRC2ukE4GEO9OMsQOBL/Fhzkh1RcIlV87Tjl4zMg5Ojeav+63qh3jmyvj6DfBoXlvNoxG/9kewI7w132+FQSmQwq8E5WLLG3u989YWC/MOj0EWvkzjUoZD9OPvoxxZcxNFD5K9AZYq/FliGd7as8G8WbYwbf7Nl9xSgLLA8yHKDVaRkuP+qbZjp8yJSsV9YMLQ==',
  }
  v3::admin_account { 'v3_dmicevski':
    user_mail  => 'dmicevski@v3.org.au',
    user_id    => '503',
    public_key => 'AAAAB3NzaC1yc2EAAAADAQABAAABAQC4E2LNMEh9l0FO/vhzWnPnoY8Ov7HC8ie6djt+J64sVacLra/kPvUzNCosYVGCn/0QLSlU3fD//VFrGnpKCCgsbwmoLDeQwaSnS1pxluIdFXXySjZ+096hSvF5MrNy4lSPYixRx6vIBPJOWCiP0Tq0T7EpugnPhevpq7ZSXOviwTr6ek2ZmgoQlBb/KFP1+/qxUkQDnd5ylM+Iu6etuNEQ87Oei4TOZg1+6Q75Mo8j0KOyVVPsuOnorlknNA0/B6F+yzSeWgR+RqMD0e5u+FbpEyTgOTSw0OsfBPpfntNAGFarsZQydOgv7EkoL1n0NW0qFAb3Yg4eZV9w3ys5YL5X',
  }
  v3::admin_account { 'v3_melvin':
    user_mail  => 'melvin@v3.org.au',
    user_id    => '504',
    public_key => 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDIAxgXVuCzQavkX5WqDuo9zJ+PvI3dxGsh4mPPkwqQ4eotKNYnXiWmj9iDdIkFkWCTF2sy1oNhiR4U5tYQJJEEtmYl9w94aM0fnlB+0k7JTaFsMfk41Q2PoHYa0oLDMoZ2CFKTyKVCJDANjXGGYfQUhOz3W0q25KZmTEMfErwJwhMmEiyliZgGkjUHcKfEDBMaN/Dtn4t52RvDxCPs57zzT8A91XaxuqAKhdra8MZVigu6WStXVUqSya3C6TQo7t7Sj3JLldQSu+G4uDYAjP/22KG7b0+HcyyVCRgihky55vd0fipCHStIqXgNsAnJjbZM3ZiNJEn5l6FdMWFQvINV',
  }
  v3::admin_account { 'v3_jwinton':
    user_mail  => 'jwinton@v3.org.au',
    user_id    => '505',
    public_key => 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDdjmhw3hUzWtT8QuGTI3ez7apV0rgPFEOT6rTl7cRxgogIEv6ATHzXsSsU4GNuq0yMLaOcAXjOXr2S5lHhkNrit8s0QOKcaj0uS7jLAmnKLN8HhfvEWErWt2A3H36+LEgQyDGOsndV915V6goEwG4bXqNEOe2Annj6F5t2R3UI9P4cG/1ydKkP7w2XCiYPfPYMkqObJG8+GdPhqBCR4BrFNphh/qBQYrakFbBqpkOzdhk++rdWTK8qu0nQozmMUEg83TE1xF6LKmt8ApiTixYowBw+ed0DBlqe8t+eoFLflLdNnYfxJpQ2fUjyd3RDhNg3dkR5inIgwv9j6BKT0R55',
  }
  v3::admin_account { 'v3_richard':
    user_mail  => 'rrothwell@v3.org.au',
    user_id    => '506',
    public_key => 'AAAAB3NzaC1yc2EAAAADAQABAAABAQCqAxDr/6iMi724kxGQBcskCHX6ATLYWNbgQMXbcVPuTOAtIyxsn70Bqe/qcIDQP6uLWh7SWdMHJX9BGFI3+AFNRffMBFmT3z6eCoaC1MsHL7pF8DoYYruTyCJQ6vAFBUD3xv9Vh5ojDQJ7VdtyBYwjcNcGetYja7aiVrsBxJDHnJWl3BVNQm2hXQ2ORL9aukL9phffEqqZ8z9O+mAgZgMboR2Z986klY7uU0A1M/VBL+UaY2IBhgyKgxLKt2SHWWn78VEu/GWkHTKIiUPq9KI1L3u5ulD4LLJUMPcFC118xTq+tqjoZzCiC6gq76ULgifzmO+F3lJaehwUDxHf5rK/',
  }

  file { '/etc/sudoers.d/sudogroup':
    ensure => file,
    owner  => root,
    mode   => '0440',
    source => 'puppet:///modules/v3/sudogroup',
  }
}
